### ISSUE TITLE
SelectionAction not being invoked in Objective-C

### ISSUE THREAD

**Issue by aamir-nazir** [AssistoLab/DropDown#104]
SelectionAction not being invoked in Objective-C, any ideas whats wrong? 
 ```
_hobbiesDropDown = [[DropDown alloc] init];
_hobbiesDropDown.selectionAction = ^(NSInteger index, NSString * item) { 
    NSLog(@"%@", item);
 };
```

**Comment by Aft3rmathpwnz** [comment]
I ran into the same issue. If it's working only with long press touch on table cell - then check that you don't hide dropdown somewhere manually (in my case it was in textFieldDidEndEditing: delegate method for UITextField that was anchorView for dropdown)
