### ISSUE TITLE
Cell height

### ISSUE THREAD

**Issue by BrankoIlic** [AssistoLab/DropDown#11]
How to change cell height (row height) in dropdown list?

**Comment by A1exandre** [comment]
Same issue here. Is there an easy way, or should we just access rowHeight of the tableview?

**Comment by kevin-hirsch** [comment]
You cannot change the height at the moment. I will add this property to the `DropDown` appearance proxy in the next milestone as discussed in #8 
Thanks!

**Comment by kevin-hirsch** [comment]
Done. You can now use it like this:
```swift
dropDownInstance.cellHeight = 80
DropDown.appearance().cellHeight = 80
```
