### ISSUE TITLE
swift 4 support

### ISSUE THREAD

**Issue by mickychen0524** [AssistoLab/DropDown#115]
any plan to update to swift 4?

**Comment by ClementLabigne** [comment]
Pretty interested in Swift 4 support too.

NahuelDevelopper forked the project and added the Swift 4 support (https://github.com/nahuelDeveloper/DropDown).

It would be great to have it in the official Pod.

**Comment by mickychen0524** [comment]
@ClementLabigne thanks for your info

**Comment by zoufishanmehdi** [comment]
I'm interested in this too. Are there any plans to officially support Swift 4 in the near future? Thank you.

**Comment by PiniginS** [comment]
There is no pod for swift 4?

**Comment by kevin-hirsch** [comment]
Until a new version of the pod is released, you can use the latest commit by doing:

```
pod 'DropDown', :git => 'https://github.com/AssistoLab/DropDown', :commit => '7a5954a'
```

**Comment by sunghwan523** [comment]
I try to add pod 'DropDown'

1.In terminal, Input ' sudo gem install cocoapods '

2. In Podfile , Add pod 'DropDown', :git => 'https://github.com/AssistoLab/DropDown', :commit => '7a5954a'

3.  Close xcode.

4. In terminal move podfile folder and then input pod install.

5. Add DropDown.. but it it not working..
Why did not working???
