### ISSUE TITLE
Not working in xcode 9

### ISSUE THREAD

**Issue by sahabe1** [AssistoLab/DropDown#119]
please see attachment
<img width="506" alt="screen shot 2017-10-08 at 12 04 58 pm" src="https://user-images.githubusercontent.com/1065015/31314559-1064fa20-ac21-11e7-8495-2724559212d4.png">

**Comment by siyavash4812** [comment]
You can easily fix it by adding @objc to the methods till a new update gets issued

**Comment by bhargavchauhan** [comment]
Please explain in briff.. 
i'm getting same error and How to fix this error...

**Comment by exera** [comment]
if you are using cocoapods add this to your Podfile and exec 'pod install', you may need to restart xcode

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if ['DropDown'].include? target.name
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '3.2'
      end
    end
  end
end

**Comment by kevin-hirsch** [comment]
Hello!
I've merged #118 (Swift 4 support) which should fix this problem.

**Comment by hammad** [comment]
@kevin-hirsch Cocoapods still has the old version. Do I need to do something on my end to fix this?

**Comment by hammad** [comment]
pod update wasn't downloading the latest Swift 4 version of DropDown. But after mentioning the git url in the pod file it finally downloaded the latest version. If anyone runs into a similar problem then try this in your pod file:

pod 'DropDown', :git=> 'https://github.com/AssistoLab/DropDown.git'
