### ISSUE TITLE
DropDown view not visible from master branch

### ISSUE THREAD

**Issue by amreshkumar** [AssistoLab/DropDown#129]
Hi,

I am using master branch (to get support for swift 4). I understand it is not very stable right now. One blocker issue i'm facing is with setup() method. The hack to dispatch async is setting view's alpha to 0 at a later point. setShowedState() was called already before this happened. Hence i'm not able to see the DropDrown. i have confirmed this with view debugger as well.

func setup() {
...
		DispatchQueue.main.async {
			//HACK: If not done in dispatch_async on main queue `setupUI` will have no effect
			self.updateConstraintsIfNeeded()
			self.setupUI()
		}
...
}

**Comment by kevin-hirsch** [comment]
Hello @amreshkumar,

Thanks for noticing!
I am indeed capable of reproducing the issue with a simple:

```swift
class ViewController: UIViewController {
   let dropDown: DropDown!

   func viewDidAppear(animated: Bool) {
      super.viewDidAppear(animated: animated)
      dropDown = DropDown()
      dropDown.dataSource = ["1", "2", "3"]
      dropDown.show()
   }
}
```

I'll work on a fix. In the meantime, you can do a workaround by instantiating in advance your DropDown instead of just before showing it, like:

```swift
class ViewController: UIViewController {
   let dropDown = DropDown()

   func viewDidAppear(animated: Bool) {
      super.viewDidAppear(animated: animated)
      dropDown.dataSource = ["1", "2", "3"]
      dropDown.show()
   }
}
```

This works for me ;)

**Comment by kevin-hirsch** [comment]
Hello again,

This should now be fixed, could you try and confirm, please? :)
Until a new version of the pod is released, you can use the latest commit by doing:

```
pod 'DropDown', :git => 'https://github.com/AssistoLab/DropDown', :commit => 'f326a13'
```

**Comment by amreshkumar** [comment]
Thanks. It works fine.
