### ISSUE TITLE
Version on cocoapods is outdated

### ISSUE THREAD

**Issue by wolczek** [AssistoLab/DropDown#130]
Version on cocoapods in not compatible with swift 4

https://cocoapods.org/?q=dropdown
Last Release | Sep 2016

**Comment by kevin-hirsch** [comment]
Hello @wolczek,

Until a new version of the pod is released, you can use the latest commit by doing:

pod 'DropDown', :git => 'https://github.com/AssistoLab/DropDown', :commit => 'f326a13'

**Comment by kevin-hirsch** [comment]
Hello @wolczek 👋 

DropDown 2.0.1 is now available via CocoaPods and Carthage with Swift 4 support and other fixes 🎉
