### ISSUE TITLE
Performance hit while loading records > 2000

### ISSUE THREAD

**Issue by jeevanRao7** [AssistoLab/DropDown#134]
Compared to Tableview it takes a while when huge records loaded.

**Comment by kevin-hirsch** [comment]
Hello @jeevanRao7,

Could you take a look at #131.
It's similar to your issue.

**Comment by jeevanRao7** [comment]
Thanks @kevin-hirsch ! Solved problem.  
by simply setting. ` dropDown.width = kTextFieldWidth`
