### ISSUE TITLE
[Objective-C] No known class method for selector 'startListeningToKeyboard'

### ISSUE THREAD

**Issue by rbustosjimenez** [AssistoLab/DropDown#138]
Hello everyone.

I'm currently working on a codebase which mixes **swift 4** and **Objective-C**. I just ran a pod install and got version 2.0.2 (I manually specified 2.0.2 on the Podfile). My AppDelegate is currently written in Objective-C. I added this line **[DropDown startListeningToKeyboard];** on the didFinishLaunchingWithOptions as recommended on the important note in the README.md, and I properly added **"@import DropDown;"** at the top of the AppDelegate.m file.

Problem is, function startListeningToKeyboard seems like not being exposed to Objective-C, as I get this message **"No known class method for selector 'startListeningToKeyboard'"** when building.

**I went and unlocked Dropdown.swift file, and added "@objc" right at the beginning of the function declaration, and everything built correctly. Does this look like a correct fix?**

To reproduce this issue, all that needs to be done is to have a project mixing Objective-C and swift 4 (had to go and set it up manually on a new project created through Xcode 9, because it defaults to swift 3.2, and the issue didn't show up when on swift 3.2), install DropDown v2.0.2 on it through cocoapods, add **"@import DropDown;"** at the top of the AppDelegate.m and **[DropDown startListeningToKeyboard];** on the didFinishLaunchingWithOptions, and build it for the simulator (or device).

Here's a screen of the specific line as seen on Xcode:

<img width="844" alt="captura de pantalla 2017-12-06 a la s 11 59 19" src="https://user-images.githubusercontent.com/11698222/33678616-daf2ffa6-da81-11e7-86ff-af9206060903.png">

Thank you for your attention and help.

**Comment by multinerd** [comment]
> Does this look like a correct fix?

Short answer: Yes
