### ISSUE TITLE
Display dropdown on scroll view

### ISSUE THREAD

**Issue by maite-manana** [AssistoLab/DropDown#152]
I've added the drodown previously with no problems. Now I'm trying to show the dropdown inside a scroll view. Thing is, the dropdown view is always shown in the same exact spot, don't matter where the "triggering button" is positioned. 
Is there any way to display the dropdown always on top/bottom of the triggerring button?

Thanxs

**Comment by saormart** [comment]
@maite-manana did you figure out how to fix it ?
Tanks!
