### ISSUE TITLE
Change backgroundColor from appearance crash

### ISSUE THREAD

**Issue by angelolloqui** [AssistoLab/DropDown#16]
When I place this line:

```
DropDown.appearance().backgroundColor = UIColor(white: 1, alpha: 0.9)
```
In my app delegate, it crashes because there is no tableView.

**Comment by kevin-hirsch** [comment]
The `backgroundColor` is actually override to:

```swift
private let tableView = UITableView()

public override var backgroundColor: UIColor? {
	get { return tableView.backgroundColor }
	set { tableView.backgroundColor = newValue }
}
```

I suppose there is a problem when using proxy `DropDown.appearance()`. I will investigate this further.
Thanks for notching!

**Comment by kevin-hirsch** [comment]
@angelolloqui On which version of Xcode and iOS were you experiencing this crash? I didn't manage to reproduce it following your instructions.

**Comment by angelolloqui** [comment]
The latest (Xcode Version 7.3 (7D175)) / iOS 9.3

I can see this issue by first placing the appearance call, before any instance of `DropDown` has been instantiated yet.

**Comment by kevin-hirsch** [comment]
Okay, I did manage to recreate the issue. It seems to appear randomly. I will fix this 👍

**Comment by kevin-hirsch** [comment]
So, this weird trick seems to fix this issue. Tell me if you still see the crash with this fix :)

```swift
private dynamic var tableViewBackgroundColor = DPDConstant.UI.BackgroundColor {
	willSet { tableView.backgroundColor = newValue }
}
	
public override var backgroundColor: UIColor? {
	get { return tableViewBackgroundColor }
	set { tableViewBackgroundColor = newValue! }
}
```
