### ISSUE TITLE
on custom nib selectionBackgroundColor not works, swift 4

### ISSUE THREAD

**Issue by 22Round** [AssistoLab/DropDown#174]
regarding document I compose custom menu cell `dropDown?.cellNib = UINib(nibName: "dropDownCell", bundle: nil)` with one `UIImageView` and `UILable`

can't make work `selectionBackgroundColor` property 
I tried this `DropDown.appearance().selectionBackgroundColor = UIColor.lightGray` but no luck ((

am I missing something?

**Comment by 22Round** [comment]
my bad, found my mistake

**Comment by uditha2233** [comment]
I also have the same issue. Im using custom cell with one UIImageView and UILable.
But the 

> selectionBackgroundColor

 property is not working. May I know what could be the issue here.
