### ISSUE TITLE
Dropdown covers the anchor

### ISSUE THREAD

**Issue by mrfarukturgut** [AssistoLab/DropDown#185]
Hi,

I am trying use this framework. It is working but one issue. Dropdown completely covers the anchor. 

<img width="529" alt="screen shot 2018-07-20 at 18 37 42" src="https://user-images.githubusercontent.com/6718272/43011445-23d7b03c-8c4c-11e8-9db3-55ec074e39fa.png">

Can you help?

**Comment by xhidnoda** [comment]
what about this?: 

// The view to which the drop down will appear on
dropDown.anchorView = view // UIView or UIBarButtonItem

**Comment by mrfarukturgut** [comment]
Yeah I did that. 

Setup of the dropdown; 

```
        dropdown.width = self.textField.frame.width
        dropdown.dataSource = ["Saatlik", "Aylık", "Haftalık"]
        dropdown.anchorView = self.textField
        dropdown.direction = .bottom
```

When textfield is started to be editing;

```
func textFieldDidBeginEditing(_ textField: UITextField) {
        print(textField.text)
        self.dropdown.show()
    }
```

**Comment by mrfarukturgut** [comment]
Apperantly this is my fault. I was in a hurry did not see `Offset` section in the doc. 
`
dropdown.bottomOffset = CGPoint(x: 0, y:(dropdown.anchorView?.plainView.bounds.height)!)`

fixed it.
