### ISSUE TITLE
selectionAction is not working

### ISSUE THREAD

**Issue by ramohanreddy** [AssistoLab/DropDown#194]
when i am selected item is not working.when taped long press then its working what is the problem here?.

**Comment by kevin-hirsch** [comment]
Hello @ramohanreddy 👋

Could you be more precise on what you are trying to do. How should it behave and what actually behaves? Seeing some code would help too!

Thanks!

**Comment by vincekinyops** [comment]
experienced this too.
a single click on an item in the dropdown's table doesnt trigger select, needed 2-3seconds press 
created a setup function like this
`private func setupDropdown(_ onLabel: UILabel) {
        dropdown.anchorView = onLabel
        dropdown.dataSource = ["sample1", "sample2", "sample3"]
        dropdown.selectionAction = { [unowned self] (index: Int, item: String) in
            print("Selected item: \(item) at index: \(index)")
            onLabel.text = item
        }
    }`

**Comment by swift4developer** [comment]
Experience the same issue. After spending 2-3 hours found the issue is because of scrollView.
You need to check with the scroll view height and dropdown view.
