### ISSUE TITLE
No such module 'DropDown'

### ISSUE THREAD

**Issue by barry-schneider** [AssistoLab/DropDown#198]
I am getting 'No such module 'DropDown' error when I try to import into swift files.

1. create a project
2. pod init
3. add pod 'DropDown', '~> 2.3.3' to pod file
4. pod install
5. open AppDelegate.swift
6. Add import DropDown
7. build
8. error

**Comment by moraesdan** [comment]
Try to do a "pod setup" then "pod update" 

*Don't forget do to this on your project folder by terminal (cd "your project folder")

**Comment by kevin-hirsch** [comment]
Hello @barry-schneider 👋

1. If you use Swift 4.2, please use at least version 2.3.4 of DropDown. Otherwise, use maximum 2.3.2.
2. You can try doing (in terminal, at root of project): `pod install`
3. Then be careful to open the **workspace** and not the **project**

You should be fine 🤗
