### ISSUE TITLE
DropDown.appearance().textFont = UIFont(name:"DroidArabicKufi",size:13)!

### ISSUE THREAD

**Issue by mouness2020** [AssistoLab/DropDown#199]
Hello,,
custom fonts not works anymore when updated to 2.3.9
only show system font .

**Comment by iwb-kevin-hirsch** [comment]
Hello @mouness2020 👋
Are you sure the issue is caused by version 2.3.9?
1. What was the previous version you were using?
2. If you downgrade to that versio does it work again?

**Comment by kevin-hirsch** [comment]
Hello @mouness2020 👋
Are you sure the issue is caused by version 2.3.9?

What was the previous version you were using?
If you downgrade to that versio does it work again?

**Comment by mouness2020** [comment]
i downgraded to 2.3.0 also problem present 
i don't know when upgraded my project to swift 4.2 the custom font not works
also not only font missed but all my all configuration ignored 
i have function called once only at didFinishLaunchingWithOptions
`
    func setupDropDown() {
        DropDown.startListeningToKeyboard()
        DropDown.appearance().textColor = UIColor.black
        DropDown.appearance().textFont = UIFont(name:"DroidArabicKufi",size:13)!
        DropDown.appearance().backgroundColor = UIColor.white
        DropDown.appearance().selectionBackgroundColor = UIColor.clear
        DropDown.appearance().cellHeight = 50
        DropDown.appearance().separatorColor = UIColor.hexColor(hex: "#e0e6e7")
        DropDown.appearance().cornerRadius = 5
        
    }`

**Comment by mouness2020** [comment]
Fixed by adding my setupDropDown() into first viewcontroller
