### ISSUE TITLE
Attempted to retain deallocated object

### ISSUE THREAD

**Issue by bendaniel10** [AssistoLab/DropDown#20]
I got this error whenever the view is about to be rendered.

_libswiftCore.dylib`_swift_abortRetainUnowned:
    0x1111def00 <+0>:  leaq   0x2ae8c(%rip), %rax       ; "attempted to retain deallocated object"
    0x1111def07 <+7>:  movq   %rax, 0x6beaa(%rip)       ; gCRAnnotations + 8
    0x1111def0e <+14>: int3   
->  0x1111def0f <+15>: nop_  

**It happens in DropDown.swift**
	_dispatch_async(dispatch_get_main_queue()) { [unowned self] in
			self.tableView.flashScrollIndicators()
		}_

**Comment by kevin-hirsch** [comment]
Hello @bendaniel10,

Can you show the code where you use the `DropDown`, please?
Note that if you don't retain the `DropDown`, it will release when right away, here's an example:
```swift
func someFunction() {
   let dropDown = DropDown()
   dropDown.anchorView = someView
   dropDown.dataSource = ["1", "2", "3"]

   dropDown.show()
   // At the end of the function, dropDown is not held by any other object so it will be freed from memory
}
```

To fix that, you will need to retain the `DropDown` like this for example:
```swift
class ViewController: UIViewController {
   let dropDown = DropDown()

   fun someFunction() {
      // Rest of the code above without the dropDown declaration
   }
}
```

Hope that helps!

**Comment by kevin-hirsch** [comment]
@bendaniel10 Did the above solution worked?

**Comment by bendaniel10** [comment]
It works now, thanks.
