### ISSUE TITLE
UIResponder errors in framework

### ISSUE THREAD

**Issue by shravanik18** [AssistoLab/DropDown#200]
Type 'UIResponder' has no member 'keyboardWillShowNotification'  - errors in Keyboard listener extension

**Comment by dakufire** [comment]
I'm having same issue

**Comment by kevin-hirsch** [comment]
Hello 👋

Can you check the [answer](https://github.com/AssistoLab/DropDown/issues/201#issuecomment-431264257) I gave for #201. Thanks! 🙏
