### ISSUE TITLE
Swift 4.1 Issues

### ISSUE THREAD

**Issue by shravanik18** [AssistoLab/DropDown#201]
<img width="635" alt="screen shot 2018-10-10 at 8 21 43 pm" src="https://user-images.githubusercontent.com/32397539/46773238-46516680-ccca-11e8-8bc9-728d4820817b.png">

UIResponder issues in swift 4.1 when using 2.3.3 version. What is the pod version for Swift 4.1 .
Swift 4.0 has 2.3.3 , swift 4.2 has 2.3.4 , Please see attachment

**Comment by kevin-hirsch** [comment]
Hello @shravanik18,

Could you try using v2.3.9 ? Do you still have the problem after installing this version of the pod?
Btw, which version of Xcode are you using?

**Comment by shravanik18** [comment]
Xcode Version is - 9.4.1

**Comment by Vaibhavi107** [comment]
Yes facing the same issue.Please help for the same
Xcode version is - 9.3
![ss](https://user-images.githubusercontent.com/20337870/47017700-91f38c80-d170-11e8-96eb-b8487946397d.png)

**Comment by ismailtosun** [comment]
same problem

**Comment by sethshal** [comment]
Getting the same issue. Used to work before. Gives me the same issue with older version too. Using xcode 10

**Comment by kevin-hirsch** [comment]
Hello everyone,

Version **2.3.2** should be the last one supporting Swift 4.1.
Can you try `pod 'DropDown', '~> 2.3.2'` and confirm that is fixes your issue?
Thanks!

**Comment by sethshal** [comment]
I upgraded to swift 4.2  and the it works now. Thanks for your help

**Comment by kevin-hirsch** [comment]
@shravanik18 @ismailtosun Have you tried the [comment](https://github.com/AssistoLab/DropDown/issues/201#issuecomment-431264257) above? Can you confirm it solves the issue?

**Comment by Vaibhavi107** [comment]
@kevin-hirsch 
Upgrading to  'DropDown', '~> 2.3.2' still gives same error.

![screenshot 2018-10-22 at 1 21 20 pm](https://user-images.githubusercontent.com/20337870/47282598-78819300-d5fd-11e8-8e83-140023818639.png)

**Comment by kevin-hirsch** [comment]
Hello @Vaibhavi107 👋 

Normally, doing `pod 'DropDown', '~> 2.3.2'` is installing 2.3.x
What you should do is `pod 'DropDown', '2.3.2'`

**Comment by Vaibhavi107** [comment]
@kevin-hirsch 
Thanks alot. It Works perfectly fine. :)

**Comment by kevin-hirsch** [comment]
Great 🤗

**Comment by Monochrome4** [comment]
@anilsutariya remove ~> , pod 'DropDown', '2.3.2'

**Comment by anilsutariya** [comment]
@Monochrome4   So what pod i can use for dropdown

**Comment by Monochrome4** [comment]
@anilsutariya I mean use pod 'DropDown', '2.3.2', remove the **~>** in pod 'DropDown', '**~>** 2.3.2'

**Comment by anilsutariya** [comment]
@Monochrome4  Let i try and do.

**Comment by Rushang007** [comment]
Upgrading to 'DropDown', ' 2.3.2' still gives same error.
![screen shot 2018-12-11 at 7 40 54 pm](https://user-images.githubusercontent.com/16713953/49806048-b5a40f00-fd7c-11e8-81fe-d4961094f342.png)

swift 4.1
xcode 9.4.1

**Comment by anilsutariya** [comment]
@Monochrome4  same error getting if remove ~>.
