### ISSUE TITLE
Hello! Please, provide bottom only corner radius feature

### ISSUE THREAD

**Issue by Said13** [AssistoLab/DropDown#202]

**Comment by Said13** [comment]
@kevin-hirsch , do you have any ideas how to do bottom only corner radius?

**Comment by xhidnoda** [comment]
can you say more specific what you want?

**Comment by xhidnoda** [comment]
can you reed about this: "maskedCorners" :  https://www.hackingwithswift.com/example-code/calayer/how-to-round-only-specific-corners-using-maskedcorners

hope that help.

**Comment by Said13** [comment]
@xhidnoda tried this. not working for this library

**Comment by xhidnoda** [comment]
yeah...that is feature we need.. can help on this... sorry  

@kevin-hirsch ...!! can you help?

**Comment by kevin-hirsch** [comment]
Hello everyone,

As proposed by @xhidnoda, it's now available via
```swift
dropDown.setupMaskedCorners([.layerMinXMinYCorner, .layerMaxXMaxYCorner])
```

on version 2.3.10 😉

**Comment by Said13** [comment]
@kevin-hirsch did you checked this new feature?

I got error 
`2018-10-16 13:30:56.397453+0300 TradeOne[14452:1276707] -[DropDown.DropDown setupMaskedCorners:]: unrecognized selector sent to instance 0x106627920
2018-10-16 13:30:56.398040+0300 TradeOne[14452:1276707] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[DropDown.DropDown setupMaskedCorners:]: unrecognized selector sent to instance 0x106627920'
*** First throw call stack:
(0x1a78bfef8 0x1a6a8da40 0x1a77d7154 0x1d44f6034 0x1a78c5810 0x1a78c74bc 0x104b212f0 0x104ad5cb4 0x104ac9478 0x106393840 0x106394de4 0x1063a2a94 0x1a784e1bc 0x1a7849084 0x1a78485b8 0x1a9abc584 0x1d4143558 0x104b2c81c 0x1a7308b94)
libc++abi.dylib: terminating with uncaught exception of type NSException
`

**Comment by Said13** [comment]
@kevin-hirsch please answer if you know why I got this error
