### ISSUE TITLE
Ambiguous use of 

### ISSUE THREAD

**Issue by DJDeth** [AssistoLab/DropDown#204]
```
dropDown.shadowOpacity
dropDown.shadowOffset
dropDown.shadowRadius
```

I'm getting Ambiguous use of 'shadowOpacity' error when setting the above values. 
I'm using XCode 10.0 with Swift 4.2
Can anyone help? 

Thanks.

**Comment by kevin-hirsch** [comment]
Hello @DJDeth 👋

This could be happening if you have defined something like:
```swift
extension UIView {
   var shadowOpacity: Float {
      get { return layer.shadowOpacity }
      set { layer.shadowOpacity = newValue }
   }
}
```

This above would conflicts with DropDown code below:

```swift
class DropDown: UIView {
	@objc public dynamic var shadowOpacity = DPDConstant.UI.Shadow.Opacity {
		willSet { tableViewContainer.layer.shadowOpacity = newValue }
		didSet { reloadAllComponents() }
	}
}
```

Is that the origin of your problem?
Hope it helps!
