### ISSUE TITLE
Xcode 9.4.1

### ISSUE THREAD

**Issue by ismailtosun** [AssistoLab/DropDown#206]
hi, I'm using swift 4.1 version and xcode 9.4.1 

and my pod like : **pod 'DropDown','2.3.9'**

but pod giving me error ? . Which version should  I use ?

**Comment by Said13** [comment]
Try ‘pod ‘DropDown’’

**Comment by kevin-hirsch** [comment]
Hello @ismailtosun,

As said in the README:
>DropDown supports Swift 4.2 since version 2.3.4.
>
>If you need Swift 4.0, use version 2.3.2:
>CocoaPods: `pod 'DropDown', '~> 2.3.2'`

Can you confirm that using version 2.3.2 is fixing you issue?

**Comment by nachi** [comment]
Still getting pod compile issues for 2.3.2 Swift 4.0

**Comment by kevin-hirsch** [comment]
Sorry I made a mistake in my answer above, it's *not* `pod 'DropDown', '~> 2.3.2'`
It is => `pod 'DropDown', '2.3.2'`
