### ISSUE TITLE
Issue with  property ".selectRow(at: index?)"

### ISSUE THREAD

**Issue by saormart** [AssistoLab/DropDown#208]
Hi there, I just updated from version 2.3.4 to 2.3.11 and my app have some issues with ".selectRow(at: index?)" property.
Just to be more specific, some screens of my app, have to select a default value from the DropDown just after it loads, and I'm using the property "selectRow".
For some reason, when I use the property "selectedItem" it's return nil on version 2.3.11.
I just created a small template with both versions of this great framework for debug, and to reproduce the problem, just follow the steps:
**Version: 2.3.4**

- After the app loads, click on the blue button "1st Get DropDown Value" and the "Pre-selected:" label will show the 1st value from the Dropdown array as: "Pre-selected: My 1st selected option"

**Version: 2.3.11**
- After the app loads, click on the blue button "1st Get DropDown Value" and the "Pre-selected:" label will not show any data from our dropdown array... just the "Pre-selected:".

Please let me know if I'm doing something wrong.
thanks!
[DropDown.zip](https://github.com/AssistoLab/DropDown/files/2496754/DropDown.zip)

**Comment by sashberd** [comment]
@saormart I have the same issue

**Comment by kevin-hirsch** [comment]
Hey guys 👋

I've pinpointed the issue here. It's should be fixed in version 2.3.12 😉
