### ISSUE TITLE
DropDown.appearance().setupCornerRadius() not working in some contexts

### ISSUE THREAD

**Issue by ryanbliss** [AssistoLab/DropDown#209]
When I use `DropDown.appearance().setupCornerRadius()`, it isn't applying to certain dropdown menus found within a `UICollectionViewCell`, while is to others. The `UICollectionViewCell` is nested inside of a `ContainerViewController` within a `SplitViewController`, if that helps. 

The menu created in the below code block is maintaining the default corner radius, as is every menu I create using this bit of code. The menu is functional, but the corner radius isn't being set. 

Everywhere else it works, so it seems to be some edge case. If anyone has any ideas I'd really appreciate it!

```
func showFancyDropdown(_ sender: UIButton, dataSource: [String], completion: @escaping (_ index: Int, _ item: String) -> Void ) {
        let dropdown = DropDown()
        dropdown.anchorView = sender.superview!.plainView
        dropdown.backgroundColor = sender.superview!.backgroundColor
        dropdown.textFont = UIFont.systemFont(ofSize: 12, weight: UIFont.Weight.black)
        dropdown.textColor = UIColor.white
        DropDown.appearance().setupCornerRadius(18)
        DropDown.appearance().roundCorners(corners: .allCorners, radius: 18)
        dropdown.dataSource = dataSource
        dropdown.show()
        dropdown.selectionAction = { (index: Int, item: String) in
            completion(index, item)
        }
}
```

![screen shot 2018-10-19 at 7 29 46 pm](https://user-images.githubusercontent.com/11748606/47249805-5b6a7b80-d3d5-11e8-8e94-26cd213e98a3.png)

Here is an example of somewhere it is working correctly, which is in a nested in a Nib within a `UITableViewCell`. This is in a view controller that is being presented modally over the left-hand side of the `SplitViewController`.

```
func setupDropdown(dataSource: [String]) {
        dropdownMenu.anchorView = dropdownIcon.plainView
        dropdownMenu.backgroundColor = UIColor.white
        dropdownMenu.textFont = UIFont.systemFont(ofSize: 12, weight: UIFont.Weight.regular)
        DropDown.appearance().setupCornerRadius(8) 
        DropDown.appearance().roundCorners(corners: .allCorners, radius: 8)
        dropdownMenu.dataSource = dataSource
        dropdownMenu.selectionAction = { [unowned self] (index: Int, item: String) in
            self.textField.text = item
            self.delegate?.selectedDropdownMenuItem(for: self.fieldId, at: index)
        }
}
```

![screen shot 2018-10-19 at 7 29 35 pm](https://user-images.githubusercontent.com/11748606/47249807-5e656c00-d3d5-11e8-9b19-9df7f9600dc6.png)

**Comment by kevin-hirsch** [comment]
Hello @ryanbliss 👋

Be aware that using `DropDown.appearance()` is modifying every DropDown instance you have in your code. So if you want all your DropDown's to have the same corner radius, you can write it once for all somewhere in your AppDelegate (for example) like so:

```swift
DropDown.appearance().setupCornerRadius(8)
```

But, if you want specific values for the corners of each DropDown, please use this instead:

```swift
dropDownMenu.setupCornerRadius(8)
```

That ☝️should solve your issue.

**Note:**

I see you have the following code:

```swift
DropDown.appearance().setupCornerRadius(8)
DropDown.appearance().roundCorners(corners: .allCorners, radius: 18)
```

I don't know what `roundCorners(corners: .allCorners, radius: 18)` is as this is not part of my library? But that is not needed. `setupCornerRadius(8)` should be enough 😉
