### ISSUE TITLE
How to add Icon and one other label

### ISSUE THREAD

**Issue by dhimansham** [AssistoLab/DropDown#220]
Hello Developer,

 I want this type of drop down list. I really confused how to add image in left side.  I trying to add imageview in dropdown Xib in  podfile and when i using the imageview then show me error
`Initializer is inaccessible due to 'internal' protection level`.

-----------------------------------------------------------

**Screen Shot I want  this type of drop down**

![screenshot 2019-01-15 at 4 04 16 pm](https://user-images.githubusercontent.com/33354025/51175045-3bb4f780-18df-11e9-8926-9998fda974a7.png)

**Comment by Gnugneus** [comment]
I would also like to insert a second label but it gives me an error: 
'[<NSObject 0x600002678600> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key longText.'

**Comment by nvdmcs** [comment]
> lass is not key value coding-comp

create custom cell , please follow instructions given in example
