### ISSUE TITLE
Swift 5.0 support

### ISSUE THREAD

**Issue by hell4opt** [AssistoLab/DropDown#229]
please!

**Comment by kevin-hirsch** [comment]
Done and available via version `2.3.13` 😉

**Comment by hell4opt** [comment]
dont work :( last xcode and swift and yout pod, with old xcode and swift work fine

**Comment by crspybits** [comment]
What was the requirement for Swift 5.0? Is there a need for projects/apps which only use Swift 5.0?

**Comment by hell4opt** [comment]
> What was the requirement for Swift 5.0? Is there a need for projects/apps which only use Swift 5.0?

on my project donr work :( before xcode update on 10.2 all worked fine

**Comment by crspybits** [comment]
Any chance to get some details on what happened?

**Comment by hell4opt** [comment]
> Any chance to get some details on what happened?

at night, my xcode was updated, after building a project with a new version, your library does not work, that is, the menu does not fall out, and if you build an old xcode, it works

**Comment by ioskiraninfosoft** [comment]
Hello, @hell4opt  same the issue with me.

**Comment by ioskiraninfosoft** [comment]
<unknown>:0: error: unable to load standard library for target 'arm64-apple-ios9.0'

**Comment by macchamps** [comment]
Hello, @hell4opt  I also facing the same issue. 
<unknown>:0: error: unable to load standard library for target 'arm64-apple-ios9.0'
