### ISSUE TITLE
update DropDown

### ISSUE THREAD

**Issue by J-Arji** [AssistoLab/DropDown#24]
hi 
i update DropDown from 1 to 1.5 but when running program app not working and error 
`  "DropDown.DropDown.anchorView.setter : weak DropDown.AnchorView?", referenced from:
`

```
Undefined symbols for architecture x86_64:
  "DropDown.DropDown.anchorView.setter : weak DropDown.AnchorView?", referenced from:
      balen.AircraftSearch.viewDidLoad () -> () in AircraftSearch.o
  "protocol witness table for __ObjC.UIView : DropDown.AnchorView in DropDown", referenced from:
      balen.AircraftSearch.viewDidLoad () -> () in AircraftSearch.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by kevin-hirsch** [comment]
Hello @J-Arji, Thanks for using this library! :)

Can you show the code where you are using the `DropDown`?
Also, how have you imported this library, manually, Cocoapods or Carthage?

**Comment by J-Arji** [comment]
i import with cocoapods an using in swift 

code:
   ```
      dropDown.dataSource = [
            "Car",
            "Motorcycle",
            "Van",
            "Truck",
            "Bus",
            "Bicycle",
            "Feet"
        ]
        
            dropDown.selectionAction = { [unowned self] (index, item) in
            self.actionButton.setTitle(item, forState: .Normal)
                let lit = item
                print(lit)
        }
      
        dropDown.direction = .Bottom
        dropDown.anchorView = actionButton
        dropDown.bottomOffset = CGPoint(x: 0, y:actionButton.bounds.height)
        // returns a String?
       
       
       
     
    }
   
    
    @IBAction func ActionTypeAir(sender: AnyObject) {
        
        if dropDown.hidden {
            dropDown.show()
        } else {
            dropDown.hide()
        }


```

**Comment by kevin-hirsch** [comment]
Thanks for the follow-up! 👍

So the only line that's causing problem seems to be
```swift
dropDown.anchorView = actionButton
```

Did you try compiling with this line in comment?

**Comment by markedwardmurray** [comment]
Hey @kevin-hirsch I just updated to v1.0 (congrats the full release) and using your pod from Objective-C view controller I experience this issue also. It appears that the `anchorView` property is not visible to Objective-C. I suspect because it is an Optional of a non-Objective-C type: http://stackoverflow.com/questions/26366082/cannot-access-property-of-swift-type-from-objective-c

**Comment by markedwardmurray** [comment]
Adding `@objc` before the protocol definition in line 18 allows it to build:

```swift
@objc public protocol AnchorView: class {

	var plainView: UIView { get }

}
```

**Comment by kevin-hirsch** [comment]
Hello @markedwardmurray, thanks! :)
`anchorView` has the type:

```swift
public protocol AnchorView: class {
	var plainView: UIView { get }
}
```

Did you try adding an `@objc` above the protocol?

**Comment by kevin-hirsch** [comment]
Ok, perfect! I'll add this now 👍

**Comment by markedwardmurray** [comment]
Yup, that's literally all it needs! I did have to avoid using the `.bounds` property on the `anchorView` from my view controller since it's now a type `id`, but that's no big deal.

**Comment by kevin-hirsch** [comment]
You can access the view through `anchorView.plainView` property, so for `bounds`, just do `anchorView.plainView.bounds` 😉

**Comment by markedwardmurray** [comment]
oh nice! thanks for the tip on that :)

**Comment by kevin-hirsch** [comment]
Done in 9d734e5. I will create a new version 1.0.1 for CocoaPods and Carthage.

**Comment by kevin-hirsch** [comment]
Actually, the reason I now use an `AnchorView` and not a `UIView` anymore is that I wanted to support `UIBarButtonItem`s that are not `UIView` subclassed. So I implemented:

```swift
 extension UIView: AnchorView {
 	public var plainView: UIView {
 		return self
 	}
 }

 extension UIBarButtonItem: AnchorView { 
 	public var plainView: UIView {
 		return valueForKey("view") as! UIView
 	}
 }
```

So `anchorView.plainView` is the same as using `anchorView` before 1.0 🙃

**Comment by kevin-hirsch** [comment]
Version 1.0.1 available on CocoaPods and Carthage! 🎉

@J-Arji Can you confirm that you don't have the issue anymore?
I leave this issue open until your confirmation.

**Comment by J-Arji** [comment]
thanks @kevin-hirsch  :)  #

**Comment by GZaccaroni** [comment]
` extension UIBarButtonItem: AnchorView { 
    public var plainView: UIView {
        return valueForKey("view") as! UIView
    }
 }`
doesn't work anymore in iOS 11

**Comment by mekalasiva** [comment]
I AM Facing the issue with Large Text in the DropDown Can u please share how to handle.

EX:

DropDown.dataSource = ["asfasdfadfhsfasfsadfsadfdsafgafskhfhskafhfahahfshfkj"]

DropDown not showing the Anchor width.
