### ISSUE TITLE
Swift Package Manager installation option

### ISSUE THREAD

**Issue by saormart** [AssistoLab/DropDown#247]
Is it possible to make it compatible with Swift Package Manager ?
Thanks!

**Comment by jaerod95** [comment]
Try using [this MR](https://github.com/AssistoLab/DropDown/pull/255), I built it for Accio support but it should work with SPM. I'd love some help testing it.
Here's the link to the [forked repo.](https://github.com/jaerod95/DropDown)

**Comment by LinusGeffarth** [comment]
I second this. Having SPM available would be nice.
