### ISSUE TITLE
Getting error after updating pod.

### ISSUE THREAD

**Issue by mukeshthawani** [AssistoLab/DropDown#25]
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </Users.../DropDown.framework> (loaded)' with name 'DropDownCell''

**Comment by mukeshthawani** [comment]
I updated the pod to the newer version but now getting a different error.

Undefined symbols for architecture i386:
  "DropDown.DropDown.anchorView.setter : weak DropDown.AnchorView?", referenced from:
      XYZ.ViewController.selectBoardButton (Swift.AnyObject) -> () in ViewController.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Which was also raised in one of the issues but I am still getting that error in v1.0.1.

**Comment by mukeshthawani** [comment]
Fixed. This issue was not related to the update in code but it was due to derived data. After deleting that it works fine.

**Comment by kevin-hirsch** [comment]
Great! 😀
Hope you are enjoying using `DropDown`! (made it with ❤️)
