### ISSUE TITLE
customCellConfiguration is not called 

### ISSUE THREAD

**Issue by basmaamahmoud** [AssistoLab/DropDown#277]
customCellConfiguration function is not called to use the logo image

  self.emplyeeButtonDropDown.cellNib = UINib(nibName: "MyCell", bundle: nil)

                self.emplyeeButtonDropDown.customCellConfiguration = { (index: Index, item: String, cell: DropDownCell) -> Void in
                
                   guard let cell = cell as? MyCell else { return }

                   // Setup your custom UI components
                   cell.logoImageView.image = UIImage(named: "pinkSpot")

                }

**Comment by MariamElennaArabAps** [comment]
@basmaamahmoud how did you solve it
