### ISSUE TITLE
I have implement  dropdown view and run the app found an error ?

### ISSUE THREAD

**Issue by jesuasir007** [AssistoLab/DropDown#304]
Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<UIView 0x1489de1d0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key optionLabel.'
terminating with uncaught exception of type NSException
CoreSimulator 802.6 - Device: iPhone 13 () - Runtime: iOS 15.4 (19E240) - DeviceType: iPhone 13

**Comment by arslankaleem7229** [comment]
update your pod in podfile to 2.3.12 and you will be good to go... like `pod 'DropDown', '2.3.12'`

**Comment by airakivela** [comment]
you solved issue??
I have met same problem..

**Comment by jesuasir007** [comment]
i have used the source file only.

**Comment by MattiaPell** [comment]
SOLVED

Open the storyboard file containing the DropDownCell, select the view and enable "Inherit Module From Target"
