### ISSUE TITLE
Xib doesn't work in xcode 7.3 swift 2.2

### ISSUE THREAD

**Issue by nghtho94** [AssistoLab/DropDown#31]
notthing happen when i click button.  The second time, when i click button dropDown.willShowAction work.
```
let dropDown = DropDown()
    var labelArr = ["Car", "Motorcycle"]
    var imageArr = ["logout.png","camera.png"]

    @IBAction func xzx(sender: AnyObject) {
        dropDown.anchorView = viewSetting
        //     dropDown.dataSource = labelArr
        DropDown.appearance().backgroundColor = UIColor.blackColor()
        //dropDown.direction = .Bottom
       // dropDown.bottomOffset = CGPoint(x: 0, y: self.viewSetting.bounds.height)
        dropDown.cellNib = UINib(nibName: "DropTableViewCell", bundle: nil)
        dropDown.customCellConfiguration = { (index: Index, item: String, cell: DropDownCell) -> Void in
            guard let cell = cell as? DropTableViewCell else { return }
            
            // Setup your custom UI components
            cell.optionLabel.text = self.labelArr[index]
            cell.imgIcon.image = UIImage(named: self.imageArr[index])
        }
        dropDown.show()
        dropDown.willShowAction = { [unowned self] in
            print("Drop down will show")
        }
    }
```
Help me pls :)

**Comment by nghtho94** [comment]
i have solved it.
Thank yo very much. :)

**Comment by scrainie** [comment]
Hi @nghtho94 , could you please share how you solved this? I'm having the same issue.

**Comment by nghtho94** [comment]
@scrainie : You must link the label in your xib to @IBOutlet in DropDown framework. Be careful, If your pod update, the referrence may be lost. You need keep the version of DropDown or copy Dropdown to your project.

**Comment by kevin-hirsch** [comment]
Hello @nghtho94,

Can you show me the code for your `DropTableViewCell`, please?
The `DropDownCell` have a 
```swift
@IBOutlet public weak var optionLabel: UILabel!
```
Linked to the original nib. Since you are subclassing it and using another nib, you have to link the new option label in the new nib to the `DropDownCell`'s `optionLabel` property.

@nghtho94 Does this new IBOutlet link remove itself with a `pod install`?

**Comment by nghtho94** [comment]
Here is my `DropTableViewCell`
`import DropDown

class DropTableViewCell: DropDownCell {

    @IBOutlet weak var imgIcon: UIImageView!
   
    override func awakeFromNib() {
        super.awakeFromNib()
        // Initialization code
    }

    override func setSelected(selected: Bool, animated: Bool) {
        super.setSelected(selected, animated: animated)

        // Configure the view for the selected state
    }
    
}`

I linked my label in my new nib to `DropDownCell's optionLabel` in Pods Folder. That why I worried about the refrerence can be lost if we have an update :).

**Comment by kevin-hirsch** [comment]
Your `DropTableViewCell` seems good!
I think there's no problem with the IBOutlet link since this info is saved in you **.xib** file and linked to your `DropTableViewCell`. But I'll investigate further to be sure what I'm saying is correct.

**Comment by nghtho94** [comment]
Thanks for your help. 👍 
Your DropDown work very nice.
