### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by nschucky** [AssistoLab/DropDown#32]
it'd be cool to have a swift 3 version, if you have any interest to create a branch i would like to help with that.

**Comment by Minitour** [comment]
@nschucky I assume you are using XCode 8 beta so I suggest you use the built in Code Conversion. It worked just fine for me.

**Edit > Convert > Modern Swift Syntax > and convert to swift 3.**

Now after that there may be some issues but they can be fixed manually.
Also make sure that the framework (in build settings) has "**Use Legacy Swift Language Version**" set to "**No**" if it isn't already.

**Comment by kevin-hirsch** [comment]
Hello @nschucky,

Good idea 👍
I will try to work on that next week, shouldn't take too long.

**Comment by tulioht** [comment]
I need version in Swift 8
XCode 8 GM out

**Comment by wmorgan6796** [comment]
I too am wondering if there is a timeline for the release of swift 3

**Comment by kevin-hirsch** [comment]
Hello everyone,

There's no precise timeline, but I plan to create a branch you will be able to use in Swift 3 by the end of the week.

**Comment by davidseek** [comment]
awesome. thanks

**Comment by kevin-hirsch** [comment]
Version 2 of DropDown is available through CocoaPods and Carthage.
Thanks everyone for using this library ❤️
