### ISSUE TITLE
DropDown frame is CGRectZero after calling show

### ISSUE THREAD

**Issue by markedwardmurray** [AssistoLab/DropDown#39]
Hi Kevin,

Thanks again for supporting this open source library. It's very well written in my opinion and I've had an easy time using it. I do have DropDown working successfully from Objective-C in one table view controller that is static-grouped and the first child of a navigation controller in a tabbar controller. Yesterday I attempted to add it a second view controller which is loaded dynamically and presented modally, which are the only differences that I can see between the uses of it.

``` objc
- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath {
    SQFBFriendTableViewCell *cell = [self.tableView dequeueReusableCellWithIdentifier:[SQFBFriendTableViewCell reuseIdentifier]];
    ... // some switching to detect the correct section, but the routing is correct

    self.multiplePhoneNumbersMenu = [[DropDown alloc] init];
    self.multiplePhoneNumbersMenu.textFont = [UIFont gothamBookAtSize:16];
    self.multiplePhoneNumbersMenu.textColor = [UIColor squadColorGrey103];
    self.multiplePhoneNumbersMenu.anchorView = cell;

     // this offset is from my implementation in the other tableview controller, toggling it has no effect on the issue
    CGFloat offset = self.multiplePhoneNumbersMenu.anchorView.plainView.bounds.size.height;
    self.multiplePhoneNumbersMenu.bottomOffset = CGPointMake(0, offset);
    self.multiplePhoneNumbersMenu.topOffset = CGPointMake(0, -offset);


    self.multiplePhoneNumbersMenu.dataSource = @[ @"Hello world" ];
    @weakify(self);
    self.multiplePhoneNumbersMenu.selectionAction = ^(NSInteger index, NSString * _Nonnull item) {
        @strongify(self);
        ... // does stuff
    };

    [self.multiplePhoneNumbersMenu show];
    // breakpoint here po's the frame as 0,0,0,0. the cell selection is highlighted, but the DropDown never appears
}
```

``` llvm
po self.multiplePhoneNumbersMenu
<DropDown.DropDown: 0x158641170; frame = (0 0; 0 0); alpha = 0; animations = { opacity=<CABasicAnimation: 0x1581db490>; }; layer = <CALayer: 0x1585247d0>>
```

I feel like I'm possibly missing something basic, but the implementation is mostly parallel to the one in my other class is the working. Any insight that you can offer would be appreciated. Thanks again!

~Mark

**Comment by kevin-hirsch** [comment]
Hello @markedwardmurray,

Thanks for using this library!
> It's very well written in my opinion and I've had an easy time using it.

Stop flattering me 🤗

Could you show me the code for your drop down, please?
What's the `anchorView` you're using?

I have in the internal `computeLayout` function this line ([719](https://github.com/AssistoLab/DropDown/blob/master/DropDown/src/DropDown.swift#L567)):

```swift
guard let window = UIWindow.visibleWindow() else { return (0, 0, 0, 0, 0, false, direction) }
```

where `visibleWindow` is implement this way:

```swift
static func visibleWindow() -> UIWindow? {
	var currentWindow = UIApplication.sharedApplication().keyWindow
	
	if currentWindow == nil {
		let frontToBackWindows = Array(UIApplication.sharedApplication().windows.reverse()) 
		
		for window in frontToBackWindows {
			if window.windowLevel == UIWindowLevelNormal {
				currentWindow = window
				break
			}
		}
	}
	
	return currentWindow
}
```

So maybe there's a problem there. Can you check it out?

Thanks!

**Comment by markedwardmurray** [comment]
It would appear that `visibleWindow()` is worked correctly:

```llvm
// line 569
(lldb) po window
▿ Optional<UIWindow>
  - Some : <UIWindow: 0x14cd55820; frame = (0 0; 375 667); autoresize = W+H; gestureRecognizers = <NSArray: 0x14cd56b60>; layer = <UIWindowLayer: 0x14cd53690>>

// line 581
(lldb) po self.anchorView
▿ Optional<AnchorView>
  - Some : <SQFBFriendTableViewCell: 0x14d256c00; baseClass = UITableViewCell; frame = (0 56; 375 48); autoresize = W; layer = <CALayer: 0x14e7acb40>>
```

**Comment by markedwardmurray** [comment]
However, `computeLayout()` seems to get called a total of 4 times, with the first call failing to retrieve the window. I would assume this first time is the initialization call?

**Comment by kevin-hirsch** [comment]
There is indeed several calls to `computeLayout` but there is always one just before showing the drop down. So this is the one that matters. (Not taking into account keyboard appearances and device rotations)

And what do you have for value in `show`function when you put breakpoints on line [761](https://github.com/AssistoLab/DropDown/blob/master/DropDown/src/DropDown.swift#L761):

```swift
if !layout.canBeDisplayed {
	hide()
	return (layout.canBeDisplayed, layout.offscreenHeight)
}
```

and below, at line [780](https://github.com/AssistoLab/DropDown/blob/master/DropDown/src/DropDown.swift#L780):

```swift
return (layout.canBeDisplayed, layout.offscreenHeight)
```

**Comment by markedwardmurray** [comment]
Mmm, yes. It trips on line 761 and calls the `hide()` on 762

**Comment by markedwardmurray** [comment]
I probably did something wrong. Using an alert controller action sheet for the time being instead

**Comment by kevin-hirsch** [comment]
Hello @markedwardmurray!

I was thinking that maybe the problem comes from the `anchorView` that is a `UITableViewCell`. Because its frame `origin` is going to be relative to the table view and not the actual window.

Could you simply put a breakpoint on the return statement of the `computeLayoutBottomDisplay` function and check those values (just after calling `show`):

- `maxY`
- `windowMaxY`
- `offscreenHeight`
- `self.tableHeight`

Thanks a lot!

**Comment by markedwardmurray** [comment]
Thanks for staying engaged! I had to move on for the time being, however. I'll check out my old commit later on my own time, hopefully by the end of the week.

**Comment by kientux** [comment]
+1 I had this problem too, but with a UITextField instead. The first time calling `-show`, dropdown didn't appear but after that it works fine.

```Objective-C
[DropDown startListeningToKeyboard];
[DropDown appearance].textFont = [UIFont systemFontOfSize:14];
_domainDropDown = [[DropDown alloc] init];
_domainDropDown.anchorView = _txtDomain;
_domainDropDown.dataSource = @[ kSkyDomainSuffix, kOrionDomainSuffix ];
weakify(self);
[_domainDropDown setSelectionAction:^(NSInteger index, NSString * _Nonnull item) {
    strongify(self);
    self.currentDomain = item;
    [(UIButton *)self.txtDomain.rightView setTitle:item forState:UIControlStateNormal];
}];

Also, if I set dropdown `anchorView` to textfield's `rightView`, it will never appear.

**Comment by mradzinski** [comment]
Having the same issue with a UITextField, but in my case it nevers shows. The ```canBeDisplayed``` property value is always ```false``` no matter what I try.

**Comment by kevin-hirsch** [comment]
Hey @kientux, @mradzinski !

Thanks for using this library :)
Could you try what I suggested [here](https://github.com/AssistoLab/DropDown/issues/39#issuecomment-246370074)
It would really help 👍

**Comment by wedkarz** [comment]
Because of this 

```
DispatchQueue.main.async {
			//HACK: If not done in dispatch_async on main queue `setupUI` will have no effect
			self.updateConstraintsIfNeeded()
			self.setupUI()
		}
```

my `dropdown.show()` is not working. 

As I debugged, I noticed that I am calling `show`, which then calls `setShowedState`, but a while after that `setup` is happening and calling `setHiddentState`.


So that I had to enclose my `sropdown.show() `into the same closure
`DispatchQueue.main.async {}` to make it work. However still things like offset aren't working properly. 

Any ideas why the HACK has to be present in library.

**Comment by markedwardmurray** [comment]
Hello @kevin-hirsch , finally got back into it. I'm currently running version 1.0.1 with a few Swift 2.3 conversions made locally. The output on a 4.7 inch iPhone in `computeBottomLayoutDisplay` is:
```
maxY: 1343.98750305176, 
windowMaxY: 647.0, 
offscreenHeight: 696.987503051758, 
self.tableHeight: 132.0
```
The anchor view is a UIButton in a cell of a static-grouped tableview on a settings screen. (This is the one I previously had working that has now stopped appearing).

The DropDown is working fine in other view controllers in which I am using the navigation bar as the anchor view, which prints:

**Comment by urosMihailovic** [comment]
Having the same issue, even drop downs in demo code have (0,0,0,0) frames :(

**Comment by indrajitsinh** [comment]
same issue , is there any update or workaround for this ?

**Comment by 4rihant** [comment]
+1 same issue as described by markedwardmurray

**Comment by agordeev** [comment]
I'm having the same problem

**Comment by kevin-hirsch** [comment]
Hello everyone,

This should now be fixed, could you try and confirm, please? :)
Until a new version of the pod is released, you can use the latest commit by doing:

```
pod 'DropDown', :git => 'https://github.com/AssistoLab/DropDown', :commit => 'f326a13'
```

**Comment by kientux** [comment]
@kevin-hirsch I can confirm this is fixed now, thanks!

**Comment by J-Arji** [comment]
DropDown frame is CGRectZero after calling show
