### ISSUE TITLE
selected index didn't reset when reset dataSource

### ISSUE THREAD

**Issue by red010182** [AssistoLab/DropDown#4]
I'm very happy with this nice work,

however I need to change the dataSource dynamically, the crash happens when the selected index of last dataSource is out of the new one, for example

dataSource A: ["a,","b"]

then, user select "b", which is index of 1

then I set new dataSource B: ["alpha"]

then when user open the dropdown menu, crash, due to the selected index is out of B's range

hope it helps

**Comment by mukeshthawani** [comment]
Hi @red010182 any solutions for this? I am facing the same problem.

**Comment by red010182** [comment]
Manually select the index after you reset the data source did solve my
problem.
Mukesh Thawani <notifications@github.com>於 2016年2月17日 週三，下午7:54寫道：

**Comment by mukeshthawani** [comment]
Thanks @red010182 it worked.

**Comment by kevin-hirsch** [comment]
Hello everyone, thanks for noticing! 👍
I will fix that for milestone 2.0
