### ISSUE TITLE
Crashing at page load 

### ISSUE THREAD

**Issue by amratab** [AssistoLab/DropDown#40]
Crashing at this point
/// Hides the drop down.
	public func hide() {
		if self == DropDown.VisibleDropDown {
			/*
			If one drop down is showed and another one is not
			but we call `hide()` on the hidden one:
			we don't want it to set the `VisibleDropDown` to nil.
			*/
			DropDown.VisibleDropDown = nil
		}

		if hidden {
			return
		}

		UIView.animateWithDuration(
			animationduration,
			delay: 0,
			options: animationExitOptions,
			animations: { [unowned self] in
				self.setHiddentState()
			},
			completion: { [unowned self] finished in
# 				**//crashing on line below**
                                self.hidden = true
				self.removeFromSuperview()
			})
	}

**Comment by amratab** [comment]
my mistake in setup

**Comment by AlbertoMrFz** [comment]
i have the same error

The solution??

**Comment by furqanmk** [comment]
@AlbertoMrFz you might be using the Swift 3 version on a Swift 2 project. If you want the version compatible with Swift 2, install the pod as 
>   pod 'DropDown', '1.0.1'

**Comment by furqanmk** [comment]
What were you doing wrong @amratab ?

**Comment by amratab** [comment]
I forgot to add this to my AppDelegate
`        DropDown.startListeningToKeyboard()
`
But if it does not work for you, I also added the following lines in my controller

`    let dropdown = DropDown()
self.dropdown.anchorView = moreOrdersView // UIView or UIBarButtonItem
        //        dropDown.show()
        // The list of items to display. Can be changed dynamically
        self.dropdown.dataSource = subordersTitles() //string list
        self.dropdown.bottomOffset = CGPoint(x: 0, y: moreOrdersView.bounds.height)
        self.dropdown.dismissMode = .automatic
        self.dropdown.direction = .bottom
        
        self.dropdown.selectionAction = { [unowned self] (index: Int, item: String) in
            self.suborderSelected(index)
        }
`
