### ISSUE TITLE
New version anytime soon?

### ISSUE THREAD

**Issue by PanMluvci** [AssistoLab/DropDown#43]
Hi... do u planning to release new version with fixed code?

![snimek obrazovky 2016-09-14 v 17 52 57](https://cloud.githubusercontent.com/assets/6050127/18519419/2d71a1c2-7aa4-11e6-845f-b001b12d43dc.png)

**Comment by kevin-hirsch** [comment]
Hello @PanMluvci, you mean working with **Xcode 8** and **Swift 3**?
There's a pull request in progress for that here: #41 
So it should come soon!

**Comment by kevin-hirsch** [comment]
Version 2 of `DropDown` is available through CocoaPods and Carthage.
