### ISSUE TITLE
Installing for Xcode 8-beta 6 yields 135 syntax errors in attempt to convert

### ISSUE THREAD

**Issue by amandascchan** [AssistoLab/DropDown#44]
When using pods to install for Xcode 8-beta 6, there's errors saying to convert to swift 2.3 or swift 3.0. After following apple's walkthrough to convert it, there's still around 135 syntax errors. 

Building the demo with Xcode 8 builds, but the simulator doesn't show up.

<img width="1279" alt="screen shot 2016-09-20 at 12 05 21 pm" src="https://cloud.githubusercontent.com/assets/5076860/18678625/9ae8e582-7f2a-11e6-939b-c738c7e073e8.png">

Unsure if DropDown isn't intended to work with Xcode 8.

**Comment by kevin-hirsch** [comment]
`DropDown` has been updated to Swift 3.0. Please update the project to the last version and everything should compile just fine.

**Comment by amandascchan** [comment]
Thank you so much, it works!

**Comment by Nidhee** [comment]
which version should be downloaded for swift 3.0 
 I am getting lots of error in xcode 8.0

**Comment by amandascchan** [comment]
I have 8.2.1 and it works. :)

**Comment by Maxnelson997** [comment]
Update to swift 3.1?
