### ISSUE TITLE
First cell is scrolled slightly up the drop down view initially. Any Solution?

### ISSUE THREAD

**Issue by bhallamohit** [AssistoLab/DropDown#49]

**Comment by kevin-hirsch** [comment]
Hello @bhallamohit!

Could you be more precise, please ?
And add a screenshot of the problem you have ?
👍

**Comment by bhallamohit** [comment]
@kevin-hirsch  OK thanx for you reply

**Comment by bhallamohit** [comment]
Any Update?

**Comment by pescadjiam** [comment]
Hey @bhallamohit, have you fixed that ?

**Comment by simmyg89** [comment]
The problem is in the selectRow function:

```
public func selectRow(at index: Index?) {
		if let index = index {
			tableView.selectRow(
				at: IndexPath(row: index, section: 0),
				animated: false,
				scrollPosition: .middle)
		} else {
			deselectRow(at: selectedRowIndex)
		}

		selectedRowIndex = index
	}
```

Setting scrollPosition from .middle to .top will solve the issue.
Created pull request #60

**Comment by Droppix** [comment]
+1

**Comment by bhallamohit** [comment]
thanks issue resolved :)

**Comment by kevin-hirsch** [comment]
Hello everyone!
#77 is merged and should resolve this issue 😉
