### ISSUE TITLE
Fix for shadowPath

### ISSUE THREAD

**Issue by markuswinkler** [AssistoLab/DropDown#7]
Great component! Found this tiny little bug:

change line 390 in Dropdown.swift from
`let shadowPath = UIBezierPath(rect: tableViewContainer.bounds)`
to
`let shadowPath = UIBezierPath(roundedRect: tableViewContainer.bounds,cornerRadius: DPDConstant.UI.CornerRadius)`

**Comment by kevin-hirsch** [comment]
Hey @markuswinkler, thanks for noticing! :)
I will fix that for the next milestone.
