### ISSUE TITLE
When continuous tapping on button, it hides dropdown forever

### ISSUE THREAD

**Issue by kartikpatel211** [AssistoLab/DropDown#72]
When continuous tapping (rapid selection) on same button, it hides dropdown forever.

**Comment by cody1024d** [comment]
I've had this issue as well, where if it's told to hide, multiple times, at the right time, the dropdown will no longer show at all

**Comment by pmvcaqr** [comment]
I have same issue

**Comment by kevin-hirsch** [comment]
Pull request #73 has been merged and fixes this issue :)
