### ISSUE TITLE
Make DPDConstants public?

### ISSUE THREAD

**Issue by markuswinkler** [AssistoLab/DropDown#8]
Your component is really well done!
Any chance that you migrate the values from DPDConstants into .appearance?
My workaround for now is to change all values in there from
`internal let`
to 
`public var`
but I guess I am not the only one who needs to change the appearance of the dropdown.
Thanks! :)

**Comment by kevin-hirsch** [comment]
Hello @markuswinkler,
I will add this to the next milestone.
